# NumPy Basics: Arrays and Vectorized Computation

In [1]:
%matplotlib inline

In [2]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## The NumPy ndarray: a multidimensional array object

In [3]:
data = randn(2, 3)

In [4]:
data

array([[ 0.689 , -0.6774, -0.0291],
       [-0.2133, -1.1922, -0.298 ]])

In [5]:
data * 10

array([[  6.8904,  -6.7744,  -0.2911],
       [ -2.1334, -11.9216,  -2.9798]])

In [6]:
data + data

array([[ 1.3781, -1.3549, -0.0582],
       [-0.4267, -2.3843, -0.596 ]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

### Creating ndarrays

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [28]:
arr1.shape

(5,)

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [17]:
print arr1.dtype
print arr2.dtype

float64
int64


In [27]:
arr = np.zeros(10, dtype=int)
arr
arr.shape

(10,)

In [22]:
arr.dtype

dtype('int64')

In [31]:
arr2 = np.zeros((1,10), dtype=int)
arr2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [33]:
np.empty((2, 3, 2), dtype=int)

array([[[-9223372036854775808,  5764616300659359517],
        [          4339400715,           4328134232],
        [          4378135360,           4346373328]],

       [[          4346373392,           4346373456],
        [-9223372036854775808, -9223372036854775808],
        [          4346347527, -9223372036854775808]]])

In [32]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [37]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [39]:
np.identity?

### Data Types for ndarrays

In [40]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print arr1.dtype
print arr2.dtype

float64
int32


In [41]:
arr = np.array([1, 2, 3, 4, 5])
print arr.dtype
float_arr = arr.astype(np.float64)
print float_arr.dtype

int64
float64


In [42]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print arr
arr.astype(np.int32)

[  3.7  -1.2  -2.6   0.5  12.9  10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [45]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [46]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [47]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 2147483648,          0, 2147483648,   41156612,
                1,  826328768,      32699], dtype=uint32)

### Operations between arrays and scalars

In [49]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [50]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [51]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [52]:
1 / arr

array([[ 1.    ,  0.5   ,  0.3333],
       [ 0.25  ,  0.2   ,  0.1667]])

In [53]:
arr ** 0.5

array([[ 1.    ,  1.4142,  1.7321],
       [ 2.    ,  2.2361,  2.4495]])

### Basic indexing and slicing

In [55]:
arr = np.arange(10)
print arr
print arr[5]
print arr[5:8]
arr[5:8] = 12
print arr

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [58]:
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[1] = 12345
print arr
arr_slice[:] = 64
arr

[    0     1     2     3     4     5 12345     7     8     9]


array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [59]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [63]:
print arr2d[0][2]
print arr2d[0, 2]

3
3


In [64]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print arr3d
arr3d[0] = old_values
arr3d

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d[1, 0]

array([7, 8, 9])

In [69]:
arr3d[1][0]

array([7, 8, 9])

#### Indexing with slices

In [71]:
arr = np.arange(10)
arr[1:6]

array([1, 2, 3, 4, 5])

In [78]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
arr2d[2, 1]

8

In [84]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [90]:
arr2d[:2, 2]

array([3, 6])

In [85]:
arr2d[1, :2]

array([4, 5])

In [91]:
print arr2d
arr2d[2, :1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7])

In [92]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [94]:
arr2d[:,0]

array([1, 4, 7])

In [ ]:
arr2d[:2, 1:] = 0

### Boolean indexing

In [103]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [95]:
data = randn(7, 4)
print data

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.6783 -1.2951 -0.3506  0.3693]
 [ 1.2039 -1.656   0.6421 -0.2728]
 [ 0.5584  0.5922  1.0029  0.0552]
 [-1.0029 -0.375  -0.965   0.8889]
 [ 1.0052  1.5715 -0.427  -1.1808]
 [ 0.2422  0.1823  1.1438  0.3033]
 [ 0.8109 -0.1031  3.5007 -1.028 ]]


In [96]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [104]:
data[names == 'Bob']

array([[-1.6783, -1.2951, -0.3506,  0.3693],
       [-1.0029, -0.375 , -0.965 ,  0.8889]])

In [106]:
data[names == 'Bob', 2:]

array([[-0.3506,  0.3693],
       [-0.965 ,  0.8889]])

In [107]:
data[names == 'Bob', 3]

array([ 0.3693,  0.8889])

In [108]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [109]:
data[-(names == 'Bob')]

array([[ 1.2039, -1.656 ,  0.6421, -0.2728],
       [ 0.5584,  0.5922,  1.0029,  0.0552],
       [ 1.0052,  1.5715, -0.427 , -1.1808],
       [ 0.2422,  0.1823,  1.1438,  0.3033],
       [ 0.8109, -0.1031,  3.5007, -1.028 ]])

In [111]:
mask = (names == 'Bob') | (names == 'Will') 
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [112]:
data[mask]

array([[-1.6783, -1.2951, -0.3506,  0.3693],
       [ 0.5584,  0.5922,  1.0029,  0.0552],
       [-1.0029, -0.375 , -0.965 ,  0.8889],
       [ 1.0052,  1.5715, -0.427 , -1.1808]])

In [113]:
data[data < 0] = 0
data

array([[ 0.    ,  0.    ,  0.    ,  0.3693],
       [ 1.2039,  0.    ,  0.6421,  0.    ],
       [ 0.5584,  0.5922,  1.0029,  0.0552],
       [ 0.    ,  0.    ,  0.    ,  0.8889],
       [ 1.0052,  1.5715,  0.    ,  0.    ],
       [ 0.2422,  0.1823,  1.1438,  0.3033],
       [ 0.8109,  0.    ,  3.5007,  0.    ]])

In [114]:
data > 0

array([[False, False, False,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [False, False, False,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True, False]], dtype=bool)

In [115]:
data[names != 'Joe'] = 7
data

array([[ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 1.2039,  0.    ,  0.6421,  0.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.2422,  0.1823,  1.1438,  0.3033],
       [ 0.8109,  0.    ,  3.5007,  0.    ]])

### Fancy indexing

In [116]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [117]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [118]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [120]:
# more on reshape in Chapter 12
arr = np.arange(32).reshape((8, 4))
print arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

In [122]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [121]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [128]:
outArr = arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]
print outArr
outArr[0,1] = 999
outArr

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


array([[  4, 999,   5,   6],
       [ 20,  23,  21,  22],
       [ 28,  31,  29,  30],
       [  8,  11,   9,  10]])

In [129]:
print arr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


### Transposing arrays and swapping axes

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

In [ ]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

In [ ]:
arr
arr.swapaxes(1, 2)

## Universal Functions: Fast element-wise array functions

In [ ]:
arr = np.arange(10)
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = randn(8)
y = randn(8)
x
y
np.maximum(x, y) # element-wise maximum

In [ ]:
arr = randn(7) * 5
np.modf(arr)

## Data processing using arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
from matplotlib.pyplot import imshow, title

In [ ]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

### Expressing conditional logic as array operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = randn(4, 4)
arr
np.where(arr > 0, 2, -2)
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
# Not to be executed

result = []
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [ ]:
# Not to be executed

np.where(cond1 & cond2, 0,
         np.where(cond1, 1,
                  np.where(cond2, 2, 3)))

In [ ]:
# Not to be executed

result = 1 * cond1 + 2 * cond2 + 3 * -(cond1 | cond2)

### Mathematical and statistical methods

In [ ]:
arr = np.random.randn(5, 4) # normally-distributed data
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(0)

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum(0)
arr.cumprod(1)

### Methods for boolean arrays

In [ ]:
arr = randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = randn(8)
arr
arr.sort()
arr

In [ ]:
arr = randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and other set logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File input and output with arrays

### Storing arrays on disk in binary format

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
!rm some_array.npy
!rm array_archive.npz

### Saving and loading text files

In [ ]:
!cat array_ex.txt

In [ ]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
arr

## Linear algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)  # equivalently np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
np.random.seed(12345)

In [ ]:
from numpy.linalg import inv, qr
X = randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Random number generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in xrange(N)]
%timeit np.random.normal(size=N)

## Example: Random Walks

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating many random walks at once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))